name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Set Permissions
        run: |
          chmod 700 $HOME/.ssh
          
      - name: Check and add host key
        run: |
          ssh-keyscan -H ec2-52-14-7-239.us-east-2.compute.amazonaws.com >> $HOME/.ssh/known_hosts

      - name: Install SSH Key
        run: |
          echo "$PRIVATE_KEY" > $HOME/.ssh/id_rsa 
          chmod 600 $HOME/.ssh/id_rsa

      - name: Debug
        run: |
          ls -la $HOME/.ssh     

      - name: Deploy to EC2   
        run: |
          scp -i $HOME/.ssh/id_rsa -r ./build/* ec2-user@ec2-52-14-7-239.us-east-2.compute.amazonaws.com:/home/ec2-user/gimnasioDeploy

      - name: Execute JAR file on EC2
        run: ssh -i $HOME/.ssh/id_rsa ec2-user@ec2-52-14-7-239.us-east-2.compute.amazonaws.com "java -jar /home/ec2-user/gimnasioDeploy/libs/gimnasioPokemon-0.0.1-SNAPSHOT.jar"
        
    env:
      PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
